@startuml

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/master/dist
!includeurl AWSPuml/AWSCommon.puml

!includeurl AWSPuml/General/User.puml
!includeurl AWSPuml/GroupIcons/Cloud.puml
!includeurl AWSPuml/General/InternetGateway.puml
!includeurl AWSPuml/NetworkingAndContentDelivery/VPCNATGateway.puml
!includeurl AWSPuml/GroupIcons/VirtualPrivateCloudVPC.puml
!includeurl AWSPuml/GroupIcons/VPCSubnetPublic.puml
!includeurl AWSPuml/GroupIcons/VPCSubnetPrivate.puml
!includeurl AWSPuml/NetworkingAndContentDelivery/VPCRouter.puml
!includeurl AWSPuml/Compute/EC2.puml
!includeurl AWSPuml/Database/RDSMySQLinstance.puml

!includeurl AWSPuml/AWSSimplified.puml

' VPC with public and private subnets (NAT)
User(user, Me, )
Cloud(aws,AWS,) {
    InternetGateway(igw, igw, )
    VirtualPrivateCloudVPC(vpc, VPC, 10.0.0.0/16) {
        VPCRouter(router, Router, "local: 10.0.0.0/16, igw: 0.0.0.0/0")
        VPCSubnetPublic(subnet_public, Public subnet, 10.0.0.0/24) {
            VPCNATGateway(nat, NAT, 198.51.100.2)
            EC2(ec2, EC2, "local: 10.0.0.6, public: 198.51.100.1")
        }
        VPCSubnetPrivate(subnet_private, Private subnet, 10.0.1.0/24) {
            RDSMySQLinstance(rds, RDS, 10.0.1.5)
        }
    }
}

note left of subnet_public
Custom route table
* local: 10.0.0.0/16
* igw: 0.0.0.0/0
end note

note left of subnet_private
Main route table
* local: 10.0.0.0/16
* nat gateway: 0.0.0.0/0
end note

user --> igw: HTTP[80, 443]
igw - router
nat -- router
ec2 - router
rds - router
ec2 -- rds: 3306

aws -[hidden]- user
vpc -[hidden]- igw
router -[hidden]- subnet_public
subnet_public -[hidden]- subnet_private

@enduml